### ISSUE TITLE
Support underscores in identifiers

### ISSUE THREAD

**Issue by pandaman64** [pandaman64/serde-query#3]

**Comment by pandaman64** [comment]
https://github.com/pandaman64/serde-query/issues/2#issuecomment-798944528

**Comment by pandaman64** [comment]
b3596dac6f8deb2cfc52449e1cdcb741285d11b9 fixed this.

**Comment by d4h0** [comment]
@pandaman64: Is there any change there could be a new release with this fix?

Not being able to use underscores without the `["field"]`-syntax was a bit unexpected, and the resulting error is pretty unhelpful.

I really like this crate, btw. :)

**Comment by pandaman64** [comment]
@d4h0 Released 0.1.4. I'm glad to see that there is a user of this crate😁

**Comment by d4h0** [comment]
Amazing – thanks a million, @pandaman64! :)
